# Generated by Django 3.1.6 on 2021-03-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoinvitro', '0002_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.CharField(max_length=25),
        ),
    ]
