# Generated by Django 3.1.6 on 2021-03-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoinvitro', '0003_auto_20210320_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
